// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Test.Persistent.Context;

namespace Test.Persistent.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Common.Domain.Contract", b =>
                {
                    b.Property<long>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ConsumerId");

                    b.Property<long>("ContractorId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Number");

                    b.Property<decimal?>("Price");

                    b.HasKey("ContractId");

                    b.HasIndex("ContractorId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Test.Common.Domain.Organization", b =>
                {
                    b.Property<long>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName");

                    b.Property<string>("Name");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            OrganizationId = 1L,
                            FullName = "Organisation 1",
                            Name = "Organisation 1"
                        },
                        new
                        {
                            OrganizationId = 2L,
                            FullName = "Organisation 2",
                            Name = "Organisation 2"
                        },
                        new
                        {
                            OrganizationId = 3L,
                            FullName = "Organisation 3",
                            Name = "Organisation 3"
                        });
                });

            modelBuilder.Entity("Test.Common.Domain.Contract", b =>
                {
                    b.HasOne("Test.Common.Domain.Organization")
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
